// Code generated by "stringer -type Type ."; DO NOT EDIT.

package ast

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[CONST-1]
	_ = x[VAR-2]
	_ = x[VECT-4]
	_ = x[BYTE-8]
	_ = x[DECL-16]
	_ = x[STRUCT-32]
	_ = x[FUNC-64]
	_ = x[FNARG-128]
}

const (
	_Type_name_0 = "CONSTVAR"
	_Type_name_1 = "VECT"
	_Type_name_2 = "BYTE"
	_Type_name_3 = "DECL"
	_Type_name_4 = "STRUCT"
	_Type_name_5 = "FUNC"
	_Type_name_6 = "FNARG"
)

var (
	_Type_index_0 = [...]uint8{0, 5, 8}
)

func (i Type) String() string {
	switch {
	case 1 <= i && i <= 2:
		i -= 1
		return _Type_name_0[_Type_index_0[i]:_Type_index_0[i+1]]
	case i == 4:
		return _Type_name_1
	case i == 8:
		return _Type_name_2
	case i == 16:
		return _Type_name_3
	case i == 32:
		return _Type_name_4
	case i == 64:
		return _Type_name_5
	case i == 128:
		return _Type_name_6
	default:
		return "Type(" + strconv.FormatInt(int64(i), 10) + ")"
	}
}
