// Code generated by "stringer -type Token"; DO NOT EDIT.

package lex

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[EOF-0]
	_ = x[COMMENT-1]
	_ = x[SYMBOL-2]
	_ = x[INTEGER-3]
	_ = x[STRING-4]
	_ = x[ADD-5]
	_ = x[SUB-6]
	_ = x[MUL-7]
	_ = x[DIV-8]
	_ = x[AND-9]
	_ = x[OR-10]
	_ = x[XOR-11]
	_ = x[SEMI-12]
	_ = x[COMMA-13]
	_ = x[LPAREN-14]
	_ = x[RPAREN-15]
	_ = x[LBRACK-16]
	_ = x[RBRACK-17]
	_ = x[LBRACE-18]
	_ = x[RBRACE-19]
	_ = x[ADDROF-20]
	_ = x[UNOP-21]
	_ = x[COLON-22]
	_ = x[BYTEOP-23]
	_ = x[LNOT-24]
	_ = x[INV-25]
	_ = x[DISJ-26]
	_ = x[NEQ-27]
	_ = x[LT-28]
	_ = x[LE-29]
	_ = x[SHL-30]
	_ = x[SHR-31]
	_ = x[GT-32]
	_ = x[GE-33]
	_ = x[EQ-34]
	_ = x[ASSIGN-35]
	_ = x[COND-36]
	_ = x[CONJ-37]
	_ = x[CONST-38]
	_ = x[DO-39]
	_ = x[DECL-40]
	_ = x[ELSE-41]
	_ = x[END-42]
	_ = x[FOR-43]
	_ = x[HALT-44]
	_ = x[IF-45]
	_ = x[IE-46]
	_ = x[LEAVE-47]
	_ = x[LOOP-48]
	_ = x[MOD-49]
	_ = x[MODULE-50]
	_ = x[OBJECT-51]
	_ = x[PACKED-52]
	_ = x[RETURN-53]
	_ = x[STRUCT-54]
	_ = x[VAR-55]
	_ = x[WHILE-56]
}

const _Token_name = "EOFCOMMENTSYMBOLINTEGERSTRINGADDSUBMULDIVANDORXORSEMICOMMALPARENRPARENLBRACKRBRACKLBRACERBRACEADDROFUNOPCOLONBYTEOPLNOTINVDISJNEQLTLESHLSHRGTGEEQASSIGNCONDCONJCONSTDODECLELSEENDFORHALTIFIELEAVELOOPMODMODULEOBJECTPACKEDRETURNSTRUCTVARWHILE"

var _Token_index = [...]uint8{0, 3, 10, 16, 23, 29, 32, 35, 38, 41, 44, 46, 49, 53, 58, 64, 70, 76, 82, 88, 94, 100, 104, 109, 115, 119, 122, 126, 129, 131, 133, 136, 139, 141, 143, 145, 151, 155, 159, 164, 166, 170, 174, 177, 180, 184, 186, 188, 193, 197, 200, 206, 212, 218, 224, 230, 233, 238}

func (i Token) String() string {
	if i < 0 || i >= Token(len(_Token_index)-1) {
		return "Token(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _Token_name[_Token_index[i]:_Token_index[i+1]]
}
